apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "mopidy.fullname" . }}
  labels:
    {{- include "mopidy.labels" $ | nindent 4 }}

data:
  mopidy.conf: |
    {{- tpl .Values.configTemplate $ | nindent 4 }}