image:
  repository: nginx
  pullPolicy: IfNotPresent

  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 6680

ingress:
  enable: true
  port: 6680
  host: mopidy.chaosdorf.space

  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

  tls:
    - hosts:
      - mopidy.chaosdorf.space
      secretName: ingress-tls

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 1Gi

nodeSelector: {}

tolerations: []

affinity: {}

config:
  snapcast:
    host: server.snapcast.chaosdorf.space
    port: 4850

configTemplate: |
  [core]
  cache_dir = /home/mopidy/cache
  config_dir = /home/mopidy/config
  data_dir = /home/mopidy/data
  max_tracklist_length = 10000
  restore_state = false

  [logging]
  verbosity = 0
  format = %(levelname)-8s %(asctime)s [%(process)d:%(threadName)s] %(name)s\n  %(message)s
  color = true
  config_file = 

  [audio]
  mixer = none
  mixer_volume = 100
  output = audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! tcpclientsink host={{ .Values.config.snapcast.host }} port={{ .Values.config.snapcast.port }}
  buffer_time = 

  [youtube]
  enabled = true
  allow_cache = 
  youtube_api_key = 
  search_results = 15
  playlist_max_videos = 20
  api_enabled = false
  channel_id = 
  musicapi_enabled = false
  musicapi_cookie = 
  musicapi_cookiefile = 
  autoplay_enabled = false
  strict_autoplay = false
  max_autoplay_length = 600
  max_degrees_of_separation = 3
  youtube_dl_package = yt_dlp

  [tunein]
  enabled = true
  timeout = 5000
  filter = 

  [somafm]
  enabled = true
  encoding = mp3
  quality = fast
  dj_as_artist = true

  [party]
  enabled = true
  votes_to_skip = 2
  max_tracks = 0
  hide_pause = false
  hide_skip = false
  style = dark.css

  [mpd]
  enabled = true
  hostname = 0.0.0.0
  port = 6600
  password = 
  max_connections = 20
  connection_timeout = 60
  zeroconf = Mopidy MPD server on $hostname
  command_blacklist = 
    listall
    listallinfo
  default_playlist_scheme = m3u

  [mixcloud]
  enabled = true
  users = 
  tags = 
  search_max = 20
  refresh_period = 600
  ignore_exclusive = true

  [iris]
  enabled = true
  country = DE
  locale = en_US
  verify_certificates = true
  snapcast_enabled = false
  snapcast_host = localhost
  snapcast_port = 1780
  snapcast_ssl = false
  snapcast_stream = Mopidy
  data_dir = /home/mopidy/data/iris

  [file]
  enabled = false  ; Extension disabled by user config.

  [http]
  enabled = true
  hostname = ::
  port = 6680
  zeroconf = Mopidy HTTP server on $hostname
  allowed_origins = 
  csrf_protection = true
  default_app = mopidy

  [m3u]
  enabled = true
  base_dir = 
  default_encoding = latin-1
  default_extension = .m3u8
  playlists_dir = 

  [softwaremixer]
  enabled = true

  [stream]
  enabled = true
  protocols = 
    http
    https
    mms
    rtmp
    rtmps
    rtsp
  metadata_blacklist = 
  timeout = 5000